# Generated by Django 6.0.3 on 2026-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_location_code_alter_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_code_if_published',
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
