# Generated by Django 6.0.3 on 2026-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_location_unique_code_if_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
