# Generated by Django 6.0.3 on 2026-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(choices=[('employee', 'Employee'), ('client', 'Client'), ('vendor', 'Vendor'), ('consultant', 'Consultant'), ('service_provider', 'Service Provider'), ('hardware_partner', 'Hardware Partner'), ('software_partner', 'Software Partner'), ('support_partner', 'Support Partner'), ('reseller', 'Reseller'), ('distributor', 'Distributor'), ('technician', 'Technician'), ('contract_staff', 'Contract Staff'), ('freelancer', 'Freelancer'), ('business_associate', 'Business Associate'), ('system_integrator', 'System Integrator')], max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
