# Generated by Django 6.0.4 on 2026-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
