# Generated by Django 6.0.3 on 2026-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_partner_is_deleted_partner_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='partners', to='myapp.company'),
        ),
    ]
