# Generated by Django 6.0.3 on 2026-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_partner_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
