# Generated by Django 6.0.4 on 2026-05-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='myapp.lead'),
        ),
    ]
