# Generated by Django 6.0.4 on 2026-05-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_company_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lead',
        ),
    ]
