# Generated by Django 6.0.4 on 2026-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_company_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='leads', to='myapp.company'),
        ),
    ]
