# Generated by Django 6.0.4 on 2026-05-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lead_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='myapp.lead')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='myapp.partner')),
            ],
            options={
                'verbose_name': 'Lead Partner',
                'verbose_name_plural': 'Lead Partners',
                'db_table': 'lead_partner',
                'ordering': ['-created_at'],
                'unique_together': {('lead', 'partner')},
            },
        ),
    ]
