# Generated by Django 6.0.4 on 2026-05-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_leadpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateTimeField()),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('message', 'Message'), ('email', 'Email')], max_length=10)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='myapp.lead')),
            ],
            options={
                'verbose_name': 'Lead Followup',
                'verbose_name_plural': 'Lead Followups',
                'db_table': 'lead_followup',
                'ordering': ['-followup_date'],
            },
        ),
    ]
