# Generated by Django 6.0.4 on 2026-05-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_leadfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start_datetime', models.DateTimeField()),
                ('schedule_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_requirement', models.TextField(blank=True)),
                ('schedule_remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_schedules', to='myapp.lead')),
            ],
            options={
                'verbose_name': 'Lead Meeting Schedule',
                'verbose_name_plural': 'Lead Meeting Schedules',
                'db_table': 'lead_meeting_schedule',
                'ordering': ['-schedule_start_datetime'],
            },
        ),
    ]
