# Generated by Django 6.0.4 on 2026-05-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_leadmeetingschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCommissionSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_for', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], max_length=10)),
                ('lead_commission_type', models.CharField(choices=[('fix_amount', 'Fix Amount'), ('percentage_wise', 'Percentage Wise'), ('recurring', 'Recurring'), ('only_for_first_billing', 'Only For First Billing'), ('every_billing', 'Every Billing')], max_length=32)),
                ('lead_commission_credit_term_condition', models.CharField(choices=[('after_billing', 'After Billing'), ('before_billing', 'Before Billing'), ('after_billing_percentage_complate', 'After Billing Percentage Complete'), ('after_billing_few_days', 'After Billing Few Days')], max_length=48)),
                ('lead_commission_type_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_commission_credit_term_condition_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_for_software', models.BooleanField(default=False)),
                ('is_peremp_wise_amount', models.BooleanField(default=False)),
                ('emp_count', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_slabs', to='myapp.lead')),
            ],
            options={
                'verbose_name': 'Lead Commission Slab',
                'verbose_name_plural': 'Lead Commission Slabs',
                'db_table': 'lead_commission_slab',
                'ordering': ['-created_at'],
            },
        ),
    ]
