# Generated by Django 6.0.4 on 2026-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_leadcommissionslab'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcommissionslab',
            name='peremp_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
