# Generated by Django 6.0.4 on 2026-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
