# Generated by Django 6.0.4 on 2026-05-13 12:54

from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    """Copy existing `location_id` and `company_id` values from the
    `myapp_userprofile` table into the newly-created many-to-many
    through tables so no data is lost during the schema change.
    This uses raw SQL to avoid depending on ORM state during migration.
    """
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        # copy locations
        cursor.execute(
            """
            INSERT INTO myapp_userprofile_locations (userprofile_id, location_id)
            SELECT id, location_id FROM myapp_userprofile WHERE location_id IS NOT NULL
            """
        )
        # copy companies
        cursor.execute(
            """
            INSERT INTO myapp_userprofile_companies (userprofile_id, company_id)
            SELECT id, company_id FROM myapp_userprofile WHERE company_id IS NOT NULL
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_userprofile_is_draft'),
    ]

    operations = [
        # first create the new many-to-many tables
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.location'),
        ),
        # copy existing FK values into the new M2M through tables
        migrations.RunPython(copy_fk_to_m2m, reverse_code=migrations.RunPython.noop),
        # finally remove the old FK columns
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
