# Generated by Django 6.0.4 on 2026-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_add_client_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_wizard_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
