# Generated by Django 6.0.4 on 2026-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_lead_last_wizard_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='lead_for_software',
        ),
        migrations.AlterField(
            model_name='leadcommissionslab',
            name='lead_for',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('software_hardware', 'Software & Hardware'), ('other', 'Other')], max_length=50),
        ),
    ]
