# Generated by Django 6.0.4 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_leadcommissionslab_lead_for_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcommissionslab',
            name='another_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
