# Generated by Django 6.0.4 on 2026-05-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_add_another_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadcommissionslab',
            old_name='amount',
            new_name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='another_amount',
        ),
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='emp_count',
        ),
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='is_peremp_wise_amount',
        ),
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='lead_for',
        ),
        migrations.RemoveField(
            model_name='leadcommissionslab',
            name='peremp_amount',
        ),
        migrations.CreateModel(
            name='LeadBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_for', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('software_hardware', 'Software & Hardware'), ('other', 'Other')], max_length=50)),
                ('is_peremp_wise_amount', models.BooleanField(default=False)),
                ('emp_count', models.PositiveIntegerField(blank=True, null=True)),
                ('peremp_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('another_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='myapp.lead')),
            ],
            options={
                'verbose_name': 'Lead Billing',
                'verbose_name_plural': 'Lead Billings',
                'db_table': 'lead_billing',
                'ordering': ['-created_at'],
            },
        ),
    ]
