# Generated by Django 6.0.4 on 2026-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_amount_leadcommissionslab_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbilling',
            name='is_for_software',
            field=models.BooleanField(default=False),
        ),
    ]
