# Generated by Django 6.0.4 on 2026-05-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_leadbilling_is_for_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcommissionslab',
            name='commission_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadcommissionslab',
            name='commission_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadcommissionslab',
            name='lead_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_slabs_by_billing', to='myapp.leadbilling'),
        ),
    ]
