# Generated by Django 6.0.4 on 2026-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_add_commission_dates_and_lead_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcommissionslab',
            name='is_percentage_wise',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            # set existing rows to True when lead_commission_type == 'percentage_wise'
            lambda apps, schema_editor: apps.get_model('myapp', 'LeadCommissionSlab').objects.filter(lead_commission_type='percentage_wise').update(is_percentage_wise=True),
            # reverse: set all to False
            lambda apps, schema_editor: apps.get_model('myapp', 'LeadCommissionSlab').objects.update(is_percentage_wise=False)
        ),
    ]
