# Generated by Django 6.0.4 on 2026-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_add_is_percentage_wise'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbilling',
            name='bill_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('yearly', 'Yearly'), ('half_yearly', 'Half Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='leadbilling',
            name='custome_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
