# Generated by Django 6.0.4 on 2026-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_leadbilling_bill_type_leadbilling_custome_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128, blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'product',
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='LeadBillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_billing', models.ForeignKey(on_delete=models.CASCADE, related_name='products', to='myapp.leadbilling')),
                ('product', models.ForeignKey(on_delete=models.CASCADE, related_name='lead_billing_links', to='myapp.product')),
            ],
            options={
                'db_table': 'lead_billing_product',
                'verbose_name': 'Lead Billing Product',
                'verbose_name_plural': 'Lead Billing Products',
            },
        ),
    ]
