# Generated by Django 6.0.4 on 2026-05-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_product_and_leadbillingproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadbillingproduct',
            options={'ordering': ['-id'], 'verbose_name': 'Lead Billing Product', 'verbose_name_plural': 'Lead Billing Products'},
        ),
    ]
