# Generated by Django 6.0.3 on 2026-05-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'verbose_name': 'Product Company',
                'verbose_name_plural': 'Product Companies',
                'db_table': 'product_company',
                'unique_together': {('product', 'company')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='products', through='myapp.ProductCompany', to='myapp.company'),
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'verbose_name': 'Product Location',
                'verbose_name_plural': 'Product Locations',
                'db_table': 'product_location',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='products', through='myapp.ProductLocation', to='myapp.location'),
        ),
    ]
